// <auto-generated />
using System;
using Master.Microservices.Orders.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Master.Microservices.Orders.DataAccess.Migrations
{
    [DbContext(typeof(OrderDataContext))]
    partial class OrderDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8666),
                            CreatedBy = 1,
                            Description = "Laptop",
                            IsAvailable = true,
                            IsEnabled = true,
                            Name = "Laptop",
                            Price = 50000m,
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8690)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8781),
                            CreatedBy = 1,
                            Description = "Printer",
                            IsAvailable = true,
                            IsEnabled = true,
                            Name = "Printer",
                            Price = 30000m,
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8783)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8787),
                            CreatedBy = 1,
                            Description = "Laptop",
                            IsAvailable = true,
                            IsEnabled = true,
                            Name = "Scanner",
                            Price = 70000m,
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8788)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8791),
                            CreatedBy = 1,
                            Description = "Written By Sadguru",
                            IsAvailable = true,
                            IsEnabled = true,
                            Name = "Karma",
                            Price = 400m,
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 875, DateTimeKind.Local).AddTicks(8792)
                        });
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 872, DateTimeKind.Local).AddTicks(4800),
                            CreatedBy = 1,
                            Description = "Electronics",
                            IsEnabled = true,
                            Name = "Electronics",
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 873, DateTimeKind.Local).AddTicks(7275)
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 873, DateTimeKind.Local).AddTicks(7896),
                            CreatedBy = 1,
                            Description = "Books",
                            IsEnabled = true,
                            Name = "Books",
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 873, DateTimeKind.Local).AddTicks(7911)
                        },
                        new
                        {
                            Id = 3,
                            CreateTime = new DateTime(2021, 10, 14, 23, 20, 15, 873, DateTimeKind.Local).AddTicks(7930),
                            CreatedBy = 1,
                            Description = "Fashion",
                            IsEnabled = true,
                            Name = "Fashion",
                            UpdateTime = new DateTime(2021, 10, 14, 23, 20, 15, 873, DateTimeKind.Local).AddTicks(7931)
                        });
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.OrderItem", b =>
                {
                    b.HasOne("Master.Microservices.Orders.DataAccess.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Master.Microservices.Orders.DataAccess.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.Product", b =>
                {
                    b.HasOne("Master.Microservices.Orders.DataAccess.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Master.Microservices.Orders.DataAccess.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
