version: '3.7'

services:

  angular-service:
    container_name: sonu-master-angular-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production